### PR TITLE
Add possibility to pass `deepCheck` property.

### PR DESCRIPTION
**Pull request by erthalion**
This allows to check nested elements even if parents are
invalid, so basically you can gather all the errors at once.

### CODE REVIEW

**Comment by erthalion** [comment]
>  The Travis CI build could not complete due to an error
```bash
$ lein2 version
No command 'lein2' found, did you mean:
 Command 'lein' from package 'leiningen' (universe)
lein2: command not found
3.27s
```

Hm?

**Comment by miikka** [comment]
The Travis configuration has slightly bitrotted. [I fixed it in master](https://github.com/metosin/scjsv/commit/fa4c75dea9dd038b4f833b4fcf7d904296f6bf39) -- if you rebase or merge master, the build should work again.

**Comment by miikka** [comment]
Being able to enable `deepCheck` makes sense to me, but I'm not sure about the API. When you look at code `(validate data true)`, it's hard to remember what the boolean in there means.

Maybe we should change it so that you'd pass a map as an optional third argument. Then it'd be `(validate data {:deep-check true})`. Or maybe it should be a parameter to `validator`/`json-validator`. What do you think, @ikitommi?

**Comment by erthalion** [comment]
Thanks for your reply. I've rebased to the latest master.

> but I'm not sure about the API.

I thought about to simulate json-schema-validator in this case (where `deepCheck` is just a boolean flag). But I agree, that it maybe confusing and `{:deep-check true}` looks much nicer.

**Comment by ikitommi** [comment]
@miikka not sure as I'm not sure of the use case. If someone want's to run selectively `deepcheck?` at runtime based on some runtime input, it could be on the returned function. But if this is mostly a forehand decision, e.g. "always on", I would go with the options going on to the `validator` & `json-validator`: would be faster and thus coherent use with our other libs (separating configuration from usage).

We could support both?

```clj
(fact "Validating JSON with deep-check"
  (let [schema (slurp (io/resource "scjsv/schema_deep.json"))
        validate (v/json-validator schema)
        validate-deep (v/json-validator schema {:deep-check? true})
        valid (slurp (io/resource "scjsv/valid.json"))
        invalid (slurp (io/resource "scjsv/deep_invalid.json"))]

    (validate valid) => nil
    (validate-deep invalid) =not=> nil

    (validate invalid {:deep-check? false}) => nil
    (validate invalid {:deep-check? true}) =not=> nil

    (count (validate invalid true)) => 2))
```

With this, the no-options `validate` would not reparse the options map, but would see the already destuctured map options via a closure to be fast.

**Comment by erthalion** [comment]
So, @miikka @ikitommi do you agree on having support for both cases?

```clojure
(validate data true)
(validate data {:deep-check? true})
```

**Comment by miikka** [comment]
Only `(validate data {:deep-check? true})`, please. Tommi's suggestion is to make it possible to "pre-configure" the validator function with `(v/json-validator schema {:deep-check? true})`.

I think it's a good idea, but even if you do just the first version, that's fine and I'll merge it.

**Comment by dchelimsky** [comment]
I'm happy to help make this happen as I need this for a project I'm working on. My opinion is this should go on the validator constructors since they are the public API. No need to expose the `validate` fn to support this. Of course, I'm biased because I have the "always on" option in mind :)

@erthalion if you want to jump on this, great, but I'd like to see this become part of the lib soon and am happy to help make it so.

**Comment by dchelimsky** [comment]
Although I guess it ultimately needs support on `validate` too, but still no need to make it public.

**Comment by erthalion** [comment]
@dchelimsky yep, unfortunately I forgot about this issue, but I have plans jump back and finish it soon.

**Comment by miikka** [comment]
I did the minimal effort work to finish this. In case you want to add this to the validator constructors, patches would be welcome.

**Pull request merged**
